credentials = {
    "USERNAME": "~~CHANGE_ME_BACKOFFICE_USER~~",
    "PASSWORD": "~~CHANGE_ME_BACKOFFICE_PASSWORD~~",
    "PUBLIC_KEY": "~~CHANGE_ME_BACKOFFICE_PUBLIC_KEY~~",
    "HMACSHA256": "~~CHANGE_ME_BACKOFFICE_HMACSHA256~~"
}